name:                crime
version:             0.1.0.0
github:              "Scott_Ranasinghe@outlook.com"
license:             BSD3
author:              "Scott S"
maintainer:          "Scott_Ranasinghe@outlook.com"
copyright:           "2018 Scott S + G37"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

description:         Please see the README on GitHub at <https://github.com/notSauce/Functional-Programming-Group-37#readme>

dependencies:
- base >= 4.7 && < 5
- HDBC
- direct-sqlite
- resourcet
- conduit
- http-conduit
- http-types
- conduit-extra
- text
- time
- bytestring
- Chart
- Chart-cairo

library:
  source-dirs: src

executables:
  bitcoin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bitcoin

tests:
  bitcoin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crime
